### ISSUE TITLE
"Open terminal here" in Dolphin doesn't work

### ISSUE THREAD

**Issue by eylenburg** [flathub/org.kde.konsole#21]
When you right-click -> "open terminal here" in Dolphin, it opens Konsole but not at the specified folder. Konsole always starts in the homo folder. This is not a problem with "native" Konsole, just the Flatpak version.

**Comment by travier** [comment]
Looks like maybe the directory is not passed to the flatpak-spwan call from Konsole. Can you file a bug upstream? Thanks

**Comment by travier** [comment]
This is https://github.com/flathub/org.kde.konsole/issues/9
