### ISSUE TITLE
[Bug] Tab title is always `flatpak-spawn`

### ISSUE THREAD

**Issue by KaKi87** [flathub/org.kde.konsole#32]
Hello,

Konsole tab titles are named after the prompt, and sometimes change when running a command, but when using the Flatpak version, these are always named `flatpak-spawn`.

It would be nice for the Flatpak version to behave like the normal version for easy tab management.

Thanks

**Comment by KaKi87** [comment]
No, my issue is about terminal emulator tabs in the Konsole app itself, not the system monitor.

Thanks

**Comment by travier** [comment]
It might not be the same place but it's likely the same underlying issue: the Konsole Flatpak uses flatpak-spawn to start a shell outside the sandbox and that's what's reported as the running process.
